# Generated by Django 4.2.9 on 2024-01-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrator'), ('superUser', 'Super user'), ('customer', 'Customer'), ('contentManager', 'Manager of content'), ('contentAdmin', 'Administrator of content'), ('productManager', 'Manager of product')], default='customer', max_length=30),
        ),
    ]
